# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EHF711tCw-ROyZ-UfPnKuPyc_zR8zJTZ
"""

import random
import string

# Function to generate password
def generate_password(length, use_letters, use_numbers, use_symbols):
    characters = ""

    if use_letters:
        characters += string.ascii_letters  # Includes both uppercase and lowercase letters
    if use_numbers:
        characters += string.digits  # Includes numbers 0-9
    if use_symbols:
        characters += string.punctuation  # Includes special symbols

    if not characters:
        print("You must select at least one character set (letters, numbers, symbols).")
        return None

    # Generate password by randomly selecting from the characters
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

# Main function to prompt user for input and generate the password
def main():
    try:
        length = int(input("Enter the desired password length: "))

        # Get user preferences for character sets
        use_letters = input("Include letters? (y/n): ").lower() == 'y'
        use_numbers = input("Include numbers? (y/n): ").lower() == 'y'
        use_symbols = input("Include symbols? (y/n): ").lower() == 'y'

        # Generate the password
        password = generate_password(length, use_letters, use_numbers, use_symbols)

        if password:
            print(f"\nGenerated password: {password}")
    except ValueError:
        print("Please enter a valid number for the password length.")

# Run the program
if __name__ == "__main__":
    main()